# Generated by Django 3.1 on 2020-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80, unique=True)),
                ('image', models.ImageField(upload_to='media/img')),
                ('price', models.IntegerField()),
                ('produuct_description', models.TextField()),
            ],
        ),
    ]
